### ISSUE TITLE
screensaver is not prohibited

### ISSUE THREAD

**Issue by avih** [wm4/mpv_backup#1]
Symptom: on win32, running `mpv --no-config clip.mp4` and waiting the system screensaver timeout ends up in the screensaver kicking in.

I bisected it down to commit 8816e1117, and specifically https://github.com/wm4/mpv_backup/commit/8816e1117ee65039dbb5700219ba3537d3e5290e#diff-762697614241cd1ca05978b2273ba6faR131

Currently it's:
```c
    bool active = !mpctx->paused && mpctx->restart_complete &&
                  mpctx->stop_play && mpctx->in_playloop && !eof;
```
And as far as I can tell, it's never set to active.

I think it should be:
```c
    bool active = !mpctx->paused && mpctx->restart_complete &&
                  !mpctx->stop_play && mpctx->in_playloop && !eof;
```

I believe it would affect all platforms.

**Comment by wm4** [comment]
not sure if I care, maybe not
